#!/bin/bash
#rofi translate script with trans-shell
#j.b. 04.10.19

ARR=()
ARR+=("English to German")
ARR+=("German to English")
ARR+=("Hungarian")
ARR+=("Hungarian&German")
menuchoice=$(printf '%s\n' "${ARR[@]}" | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "Select Langauge(s):    ")


if [ "$menuchoice" = "Hungarian" ]; then
choiceWord=$(printf "" | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "Translate into Hungarian:   ")
CHOICE=$(trans :hu "$choiceWord" | sed -n '3p;4p' |awk -F1m '{print $2}' | sed -r 's/.....$//g')
CHOICEtime=$(printf " $(echo $CHOICE)"  | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "$choiceWord: ")
espeak -vhu -s 100 "$CHOICE"
exit 0
fi


if [ "$menuchoice" = "English to German" ]; then
choiceWord=$(printf "" | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "Translate into German:   ")
CHOICE=$(trans :de "$choiceWord" | sed -n '3p;4p' |awk -F1m '{print $2}' | sed -r 's/.....$//g')
CHOICEtime=$(printf " $(echo $CHOICE)"  | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "$choiceWord: ")
exit 0
fi


if [ "$menuchoice" = "German to English" ]; then
choiceWord=$(printf "" | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "Translate into English:   ")
CHOICE=$(trans de:en "$choiceWord" | sed -n '3p;4p' |awk -F1m '{print $2}' | sed -r 's/.....$//g')
CHOICEtime=$(printf " $(echo $CHOICE)"  | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "$choiceWord: ")
exit 0
fi



if [ "$menuchoice" = "Hungarian&German" ]; then

choiceWord=$(printf "" | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "Translate into Hungarian and German:   ")
CHOICE0=$(trans :hu "$choiceWord" | sed -n '3p;4p' |awk -F1m '{print $2}' | sed -r 's/.....$//g')
CHOICE1=$(trans :de "$choiceWord" | sed -n '3p;4p' |awk -F1m '{print $2}' | sed -r 's/.....$//g')
TRR=()
TRR+=("Hungarian:	$CHOICE0")
TRR+=("German:		$CHOICE1")
translateDisp=$(printf '%s\n' "${TRR[@]}" | rofi -dmenu -config /usr/share/rofi/themes/fullbar.rasi -p "$choiceWord: ")
	if [ "$translateDisp" = "Hungarian:	$CHOICE0" ]; then
		echo "$CHOICE0" | xsel -ib
		exit 0
	fi
	if [ "$translateDisp" = "German:		$CHOICE1" ]; then
		echo "$CHOICE1" | xsel -ib
		exit 0
	fi
exit 0
fi

